services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sada
      MYSQL_PASSWORD: sada
